name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
jobs:
  check-applications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with: 
          go-version: 1.15
      - run: go test
      - run: go run testmath.go

  generate-build:
    needs: check-applications
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker images
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: vfjansen/fullcycle-go-build-on-gh-action:latest
          
